name: Go CI

on:
  push:
    branches:
      - main  # Adjust branch name if needed
  pull_request:
    branches:
      - main  # Adjust branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17  # Adjust Go version as needed

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      # Add more steps as needed (e.g., linting, building)

